
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roljsmhhptuwtsbirsxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbGpzbWhocHR1d3RzYmlyc3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDg4NTMsImV4cCI6MjA1NzIyNDg1M30.SY6MAzg8mCVsMF0L2wseIIqET5ROq48wizK-RxeaNJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check if the current user is a teacher
export const isTeacher = async (): Promise<boolean> => {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      return false;
    }
    
    // Get the user's profile to check their role
    const { data: profile, error } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single();
    
    if (error || !profile) {
      console.error('Error fetching user profile:', error);
      return false;
    }
    
    return profile.role === 'teacher';
  } catch (error) {
    console.error('Error checking teacher role:', error);
    return false;
  }
};
